//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelFirst
{
    using System;
    
    public enum Category : int
    {
        Sports = 0,
        Food = 1,
        Shopping = 2,
        HealthAndBeauty = 3
    }
}
