//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : Person
    {
        public Customer()
        {
            this.Coupons = new HashSet<Coupon>();
            this.OrderedCoupons = new HashSet<OrderedCoupon>();
        }
    
        public double Location_x { get; set; }
        public double Location_y { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<OrderedCoupon> OrderedCoupons { get; set; }
        public virtual Location Location { get; set; }
    }
}
