//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseModelContext : DbContext
    {
        public DatabaseModelContext()
            : base("name=DatabaseModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Person> People { get; set; }
        public DbSet<Business> Businesses { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<OrderedCoupon> OrderedCoupons { get; set; }
        public DbSet<Location> Locations { get; set; }
    }
}
