//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Coupons = new HashSet<Coupon>();
            this.Customers = new HashSet<Customer>();
        }
    
        public double x { get; set; }
        public double y { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
